# Config file for automatic testing at travis-ci.org
language: python
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install tox coveralls
  - make test

# command to run tests using coverage, e.g. python setup.py test
script:
  - tox
env:
  - TOXENV=py27-16
  - TOXENV=py26-16
  - TOXENV=py27-15
  - TOXENV=py26-15
# report coverage to coveralls.io
after_success: coveralls
